//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emka.PracticeLooper.Mobile {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Emka.PracticeLooper.Mobile.AppResources.en-US", typeof(AppResources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Spotify {
            get {
                return ResourceManager.GetString("Spotify", resourceCulture);
            }
        }
        
        internal static string AudioFile {
            get {
                return ResourceManager.GetString("AudioFile", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        internal static string LoopStartPosition {
            get {
                return ResourceManager.GetString("LoopStartPosition", resourceCulture);
            }
        }
        
        internal static string LoopEndPosition {
            get {
                return ResourceManager.GetString("LoopEndPosition", resourceCulture);
            }
        }
        
        internal static string LoopsDetailsView_Title {
            get {
                return ResourceManager.GetString("LoopsDetailsView_Title", resourceCulture);
            }
        }
        
        internal static string SpotifySearchView_Title {
            get {
                return ResourceManager.GetString("SpotifySearchView_Title", resourceCulture);
            }
        }
        
        internal static string SpotifySearchView_SearchBox_Placeholder {
            get {
                return ResourceManager.GetString("SpotifySearchView_SearchBox_Placeholder", resourceCulture);
            }
        }
        
        internal static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        internal static string SettingsView_DarkMode {
            get {
                return ResourceManager.GetString("SettingsView_DarkMode", resourceCulture);
            }
        }
        
        internal static string SettingsView_AppVersion {
            get {
                return ResourceManager.GetString("SettingsView_AppVersion", resourceCulture);
            }
        }
        
        internal static string SettingsView_ListView_Header {
            get {
                return ResourceManager.GetString("SettingsView_ListView_Header", resourceCulture);
            }
        }
        
        internal static string SettingsView_NoUpgradesDescription {
            get {
                return ResourceManager.GetString("SettingsView_NoUpgradesDescription", resourceCulture);
            }
        }
        
        internal static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        internal static string Error_Content_General {
            get {
                return ResourceManager.GetString("Error_Content_General", resourceCulture);
            }
        }
        
        internal static string Error_Content_CouldNotCreateSession {
            get {
                return ResourceManager.GetString("Error_Content_CouldNotCreateSession", resourceCulture);
            }
        }
        
        internal static string Error_Content_CouldNotPlaySong {
            get {
                return ResourceManager.GetString("Error_Content_CouldNotPlaySong", resourceCulture);
            }
        }
        
        internal static string Error_Content_CouldNotDeleteSong {
            get {
                return ResourceManager.GetString("Error_Content_CouldNotDeleteSong", resourceCulture);
            }
        }
        
        internal static string Error_Content_CouldNotCreateLoop {
            get {
                return ResourceManager.GetString("Error_Content_CouldNotCreateLoop", resourceCulture);
            }
        }
        
        internal static string Error_Content_CouldNotDeleteLoop {
            get {
                return ResourceManager.GetString("Error_Content_CouldNotDeleteLoop", resourceCulture);
            }
        }
        
        internal static string Error_Content_CouldNotConnectToStore {
            get {
                return ResourceManager.GetString("Error_Content_CouldNotConnectToStore", resourceCulture);
            }
        }
        
        internal static string Error_Content_CouldNotPurchaseItem {
            get {
                return ResourceManager.GetString("Error_Content_CouldNotPurchaseItem", resourceCulture);
            }
        }
        
        internal static string Error_Content_StoreUnavailable {
            get {
                return ResourceManager.GetString("Error_Content_StoreUnavailable", resourceCulture);
            }
        }
        
        internal static string Error_Content_BillingUnavailable {
            get {
                return ResourceManager.GetString("Error_Content_BillingUnavailable", resourceCulture);
            }
        }
        
        internal static string Error_Content_PaymentInvalid {
            get {
                return ResourceManager.GetString("Error_Content_PaymentInvalid", resourceCulture);
            }
        }
        
        internal static string Error_Content_PaymentNotAllowed {
            get {
                return ResourceManager.GetString("Error_Content_PaymentNotAllowed", resourceCulture);
            }
        }
        
        internal static string Error_Content_RestoreFailed {
            get {
                return ResourceManager.GetString("Error_Content_RestoreFailed", resourceCulture);
            }
        }
        
        internal static string Error_Content_CouldNotConnectToSpotify {
            get {
                return ResourceManager.GetString("Error_Content_CouldNotConnectToSpotify", resourceCulture);
            }
        }
        
        internal static string Hint_Caption_AlreadyPurchased {
            get {
                return ResourceManager.GetString("Hint_Caption_AlreadyPurchased", resourceCulture);
            }
        }
        
        internal static string Hint_Content_AlreadyPurchased {
            get {
                return ResourceManager.GetString("Hint_Content_AlreadyPurchased", resourceCulture);
            }
        }
        
        internal static string Hint_Caption_SlowConnection {
            get {
                return ResourceManager.GetString("Hint_Caption_SlowConnection", resourceCulture);
            }
        }
        
        internal static string Hint_Content_SlowConnection {
            get {
                return ResourceManager.GetString("Hint_Content_SlowConnection", resourceCulture);
            }
        }
        
        internal static string Hint_Caption_FileTooLong_Caption {
            get {
                return ResourceManager.GetString("Hint_Caption_FileTooLong_Caption", resourceCulture);
            }
        }
        
        internal static string Hint_Content_FileTooLon_Content {
            get {
                return ResourceManager.GetString("Hint_Content_FileTooLon_Content", resourceCulture);
            }
        }
        
        internal static string Hint_Caption_SpotifyMissing_Caption {
            get {
                return ResourceManager.GetString("Hint_Caption_SpotifyMissing_Caption", resourceCulture);
            }
        }
        
        internal static string Hint_Content_SpotifyMissing_Content {
            get {
                return ResourceManager.GetString("Hint_Content_SpotifyMissing_Content", resourceCulture);
            }
        }
        
        internal static string Prompt_Caption_NewLoop {
            get {
                return ResourceManager.GetString("Prompt_Caption_NewLoop", resourceCulture);
            }
        }
        
        internal static string Prompt_Content_NewLoop {
            get {
                return ResourceManager.GetString("Prompt_Content_NewLoop", resourceCulture);
            }
        }
        
        internal static string Prompt_Content_NewLoo_NamePlaceholder {
            get {
                return ResourceManager.GetString("Prompt_Content_NewLoo_NamePlaceholder", resourceCulture);
            }
        }
    }
}
